### PR TITLE
Update rack dependency to support 1.1 <= rack < 3.0

### PR DESCRIPTION
**Pull request by stmllr**
rack 2.0 has been released on May 07. I don't see any related breaking changes.

### CODE REVIEW

**Comment by stmllr** [comment]
sinatra currently conflicts with encrypted_cookie because of rack 2.0 requirements

**Comment by ckuttruff** [comment]
Thanks for this!  Just ran into this issue and glad others are still using this gem and interested in keeping it up to date.  Thanks for your work @cvonkleist et al.

**Comment by ckuttruff** [comment]
gonna clone your fork and test this out now, cheers

**Comment by ckuttruff** [comment]
Actually... this might be properly supported in sinatra now without a separate gem:
https://github.com/sinatra/sinatra#using-sessions

not sure how the security compares, but yeah :/

**Comment by stmllr** [comment]
@ckuttruff Sinatra supports signing cookies. The encrypted_cookie gem supports signing *and* encrypting cookies. This is a big difference.

**Comment by ckuttruff** [comment]
@stmllr thanks for that clarification.  Wasn't sure if they had implemented that or not in Sinatra 2.0

Ran into an error when running this branch the other day.  Will double check what it was, post here, and try to troubleshoot

**Comment by ckuttruff** [comment]
nm, sorry, error was something else.  PR looks good to me!
:shipit:   :)

**Comment by cvonkleist** [comment]
Hi, guys. Sorry for the slow response. Thanks, @stmllr for submitting this PR, and thanks @ckuttruff 
 for reviewing! I'm merging it now.

**Comment by cvonkleist** [comment]
Thanks for all your help, everyone. I finally pushed version 0.0.5 of the encrypted_cookie gem today:

  https://rubygems.org/gems/encrypted_cookie

**Pull request merged**
